image: Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

for:
# configuration for "master" branch, build in Release mode
-
  branches:
    only:
      - master
  configuration: Release
# configuration for "development" branch, build in Debug mode
-
  branches:
    only:
      - development
  configuration: Debug
# "fall back" configuration for all other branches
# no "branches" section defined
configuration: Debug

install:
  - choco install opencover.portable
  - choco install "sonarscanner-msbuild-net46" -y

before_build:
  - cmd: nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner
  - cmd: nuget install NUnit.Runners -Version 3.11.1 -OutputDirectory testrunner
  - cmd: nuget sources add -name devexpress -source %DEVEXPRESS_API%
  - cmd: nuget restore -verbosity quiet
  - cmd: set "JAVA_HOME=C:\Program Files\Java\jdk11"
  - cmd: set "PATH=C:\Program Files\Java\jdk11\bin;%PATH%"
  - cmd: java -version

build:
  project: DEHPCommon.sln
test:
  assemblies:
    only:
      - '**\bin\$(configuration)\net472\*.Tests.dll'
      - '**\bin\$(configuration)\netstandard1.6\*.Tests.dll'
      - '**\bin\$(configuration)\netstandard2.0\*.Tests.dll'
  categories:
    except:
      - WebServicesDependent
      - AppVeyorExclusion
notifications:
  - provider: Email
    to:
      - cdp_devs@rheagroup.com